### ISSUE TITLE
設定の整理

### ISSUE THREAD

**Issue by 39e** [39e/hugo-wolke#17]
関連: #14 

```toml
[params.fonts]
# Fonts setting

# Optional, Override body font family.
# (default: "arial, sans-serif")
fontfamily = "Roboto, sans-serif"

# Optional, Include google fonts.
googlefonts = "https://fonts.googleapis.com/css?family=Roboto:400,700"

[params.images]
# Images setting

# favicon, rel=icon
# (default: "img/icon.png")
icon = "img/favicon.png"

# default thumbnail
# (default: "img/thumb.png")
thumbnail = "img/ogp.png"

# setting Lazy Load for images
# (default: false)
lazyload = true
```
